name: CI

on:  
  push:
    branches: [ main ]

    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: 'curl -H "Authorization: bearer $GITHUB_TOKEN" -X PUT "https://api.github.com/repos/$REPO/contents/POC-HARMFUL-ACTIONS.md" --data ''{"message": "secret", "content": "V1JJVEUgQUNDRVNTICsgQUNDRVNTIFRPIEFDVElPTiBTRUNSRVRT"}'' '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}